/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.librarysystem;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author DELL
 */
public class LibrarySystem extends javax.swing.JFrame {


    /**
     * Creates new form LibrarySystem
     */
    public LibrarySystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bookregistration = new javax.swing.JButton();
        studentregistration = new javax.swing.JButton();
        borroebooks = new javax.swing.JButton();
        returnbook = new javax.swing.JButton();
        payfine = new javax.swing.JButton();
        loanhistory = new javax.swing.JButton();
        loanhistory1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setText("Libraray Management System");

        bookregistration.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        bookregistration.setText("Book Registration");
        bookregistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookregistrationActionPerformed(evt);
            }
        });

        studentregistration.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        studentregistration.setText("Student Registration");
        studentregistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentregistrationActionPerformed(evt);
            }
        });

        borroebooks.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        borroebooks.setText("Borrow Book");
        borroebooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borroebooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borroebooksActionPerformed(evt);
            }
        });

        returnbook.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        returnbook.setText("Return Book");
        returnbook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbookActionPerformed(evt);
            }
        });

        payfine.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        payfine.setText("Pay Fine");
        payfine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payfine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payfineActionPerformed(evt);
            }
        });

        loanhistory.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        loanhistory.setText("Book Loan History");
        loanhistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loanhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanhistoryActionPerformed(evt);
            }
        });

        loanhistory1.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        loanhistory1.setText("Paid Fine");
        loanhistory1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loanhistory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanhistory1ActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        exit.setText("Exit");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bookregistration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentregistration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loanhistory, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(loanhistory1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payfine, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borroebooks, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnbook, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookregistration, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentregistration, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanhistory1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borroebooks, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnbook, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payfine, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentregistrationActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegistration().setVisible(true);
            }
        });
    }//GEN-LAST:event_studentregistrationActionPerformed

    private void borroebooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borroebooksActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowBooks().setVisible(true);
            }
        });
    }//GEN-LAST:event_borroebooksActionPerformed

    private void returnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbookActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBooks().setVisible(true);
            }
        });
    }//GEN-LAST:event_returnbookActionPerformed

    private void payfineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payfineActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayFine().setVisible(true);
            }
        });
    }//GEN-LAST:event_payfineActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int yes = JOptionPane.showConfirmDialog(null, "Do you want to exit?", "Message", YES_NO_OPTION);

        if (yes == JOptionPane.YES_OPTION) {
            System.exit(1);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void bookregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookregistrationActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRegistration().setVisible(true);
            }
        });
    }//GEN-LAST:event_bookregistrationActionPerformed

    private void loanhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanhistoryActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookloanhistory().setVisible(true);
            }
        });
    }//GEN-LAST:event_loanhistoryActionPerformed

    private void loanhistory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanhistory1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaidFine().setVisible(true);
            }
        });
    }//GEN-LAST:event_loanhistory1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarySystem().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookregistration;
    private javax.swing.JButton borroebooks;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loanhistory;
    private javax.swing.JButton loanhistory1;
    private javax.swing.JButton payfine;
    private javax.swing.JButton returnbook;
    private javax.swing.JButton studentregistration;
    // End of variables declaration//GEN-END:variables
}
